sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eJbBukovbScPe8W/vmvTVf2P1iYexWiQU+aZFVc78nXPad5rqbvJoGgeMWynGg5kj1707k+/muSPRFLHB2zjMjXC6EjybOIp0EGc7Srq2wYnI3H5gAyJTokEk8k0HXbq8y9rGF+GJpSIPXg6D/4IE8mpLUfYv0ik3zrK8V8WZTmTL2IAKXQz8HXni51r3cGRnQV0L85ItlVDkfOkHXGcuZeYKNpeRAGVdRMdrb1teZSlYRdrkuvHkvoluj6Xr4Dn+nDf8irZrBwWQQmbxumkWxpvGreU2kaDa0E0J3uRrrRvP/vrjlRB6iWHbvf+EMCOnUzdv4jAHHVDDV1/uYP4zUspHd/1EmIYpCSahOj737ih6FIIQLEqZcZso7nKmn++fgQ7t/On00MEb8QNQ+SvyQm9um4F6hV9iAbcBlCiqMe/uZvINp4gAsnDPsCnkzGesQbTo8FUfsfcGdzm5C3rmD1C1q7EswECMxDLL2X7UwGLkjimAPTR9stsqq9WM81zqUvsow15pOTltQEZJErfJjKNHtUtI/a7Gl+US7lbwXsOElWBQreNvfZ34yi1ZQubGww75pVHbN1K1zD+10qf/VAj4lSG0StxVZy2UsiIzDiTfcFRH7imL9+arUx6IMNsA5zamhwG55qE/I2+xozOkprXw51CobGs9IGd0lM6pQo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Home-Book-of-Verse---Volume-3_2621
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy